# ==============================================================================
# Script:   fig_exvivo_pca_exploratory.R
# Chapter:  [1] — exvivo bulk rnaseq
# Step:     Terminal figure script — loads from Checkpoint D
#           Preceded by: 04_exvivo_correction.R
#
# Description:
#   Produces PCA-based visualisations comparing the three normalised/corrected
#   expression matrices generated by 04_exvivo_correction.R:
#
#     1. VST — unadjusted variance-stabilised counts
#     2. SVA-corrected — surrogate-variable-adjusted VST matrix
#     3. Study-corrected — limma removeBatchEffect()-adjusted VST matrix
#
#   For each matrix, make_pca_panels() generates a named panel set:
#     $pca_<label>     — one PCA colour panel per entry in color_vars (see below)
#     $scree           — scree plot (PC1–10)
#     $pearson_heatmap — PCs vs continuous_vars
#     $kruskal_heatmap — PCs vs categorical_vars
#
#   Two figure layouts are available, each accepting one or two panel sets:
#     assemble_pca_overview()      — PCA + scree + heatmaps (portrait, A4)
#     assemble_pca_metafeatures()  — PCA coloured by metadata features (landscape)
#
#   To produce a single-matrix figure, pass only `panels_a`.
#   To compare two matrices, pass both `panels_a` and `panels_b`.
#   Any combination of vst_panels, sva_panels, study_panels is valid.
#
# Inputs:
#   - rds/chapter_01/exvivo_normalisation.rds
#         List: $vst, $sva_adjusted, $study_adjusted, $metadata_full
#         Produced by 04_exvivo_correction.R
#
# Outputs (adjust file names and panel sets as needed — see bottom of script):
#   - figures/chapter_01/fig_exvivo_normalisation_pca.svg
#   - figures/chapter_01/fig_exvivo_normalisation_pca_metafeatures.svg
#
# Environment:
#   All scripts in this repository are intended to run inside a Docker
#   container. The image used for the RStudio session is available at:
#     https://hub.docker.com/r/stodo3569/rstudio-server_microglial-identity
#   See docker/ in this repository for the Dockerfile and build instructions.
#   Common utility functions shared across scripts are sourced from
#   common/R/00_functions.R (see repository root).
# ==============================================================================

source("microglial-identity/common/R/00_functions.R")

# ==============================================================================
# RDS management
# ==============================================================================
# This is a terminal figure script: it reads one input RDS and produces no
# output RDS (SAVE_OUTPUT_RDS is always FALSE for figure scripts).
#
#   Input:
#     rds/chapter_01/exvivo_normalisation.rds     List: $vst, $sva_adjusted,
#                                                  $study_adjusted, $metadata_full
#
# Two ways to load the input RDS — set the flag below accordingly:
#
#   1) Load from Zenodo (LOAD_INPUT_RDS = TRUE, default):
#      Downloads exvivo_normalisation.rds from Zenodo if not present locally,
#      then runs this script in full.
#
#   2) Load from local file (LOAD_INPUT_RDS = FALSE):
#      Expects exvivo_normalisation.rds to be present locally at
#      rds/chapter_01/exvivo_normalisation.rds (produced by running
#      04_exvivo_correction.R).
#
# Replace XXXXXXX in ZENODO_BASE with the actual Zenodo record ID once the
# dataset has been deposited.
# ==============================================================================

ZENODO_BASE <- "https://zenodo.org/records/XXXXXXX/files/chapter_01/rds"

# ── Input RDS ────────────────────────────────────────────────────────────────
input_rds <- list(
  normalisation = "rds/chapter_01/exvivo_normalisation.rds"  # List: $vst, $sva_adjusted, $study_adjusted, $metadata_full
)

LOAD_INPUT_RDS <- TRUE

if (LOAD_INPUT_RDS) {
  for (rds_name in names(input_rds)) {
    local_path <- input_rds[[rds_name]]
    local_file <- basename(local_path)
    if (file.exists(local_path)) {
      message(local_file, " already exists locally — skipping download.")
    } else if (file.exists(local_file)) {
      message(local_file, " found in working directory — skipping download.")
      local_path <- local_file
    } else {
      url <- paste0(ZENODO_BASE, "/", local_file)
      message("Downloading ", local_file, " from Zenodo...")
      download.file(url, destfile = local_path, mode = "wb")
    }
  }
  checkpoint_d   <- readRDS(local_path)
  vst            <- checkpoint_d$vst
  sva_adjusted   <- checkpoint_d$sva_adjusted
  study_adjusted <- checkpoint_d$study_adjusted
  metadata       <- checkpoint_d$metadata_full
  remove(checkpoint_d)
}

# ── Output (figures only — no RDS produced by terminal scripts) ──────────────
SAVE_OUTPUT_RDS <- FALSE

dir.create("figures/chapter_01", recursive = TRUE, showWarnings = FALSE)

# ==============================================================================
# Set up working environment
# ==============================================================================

set.seed(123)

library(tidyverse)
library(patchwork)
library(broom)

# ==============================================================================
# PCA variable specification
# ==============================================================================
# color_vars       : named character vector — label (used in legend title and
#                    panel name) → metadata column name. The FIRST entry is
#                    used as the primary PCA (drives the scree plot and both
#                    heatmaps). Add, remove, or reorder entries freely; the
#                    assembly functions adapt automatically.
# continuous_vars  : metadata columns for the Pearson correlation heatmap.
# categorical_vars : metadata columns for the Kruskal-Wallis heatmap.

color_vars <- c(
  study  = "study",
  age    = "age",
  sex    = "sex_imputed",
  region = "region",
  origin = "source_if_ex_vivo"
)

continuous_vars  <- c("age", "mapping_rate", "total_reads", "sample_gene_count")
categorical_vars <- c("study", "sex_imputed", "source_if_ex_vivo", "region")

# ==============================================================================
# Build panel sets — one per matrix
# ==============================================================================
# Each call to make_pca_panels() returns a named list of ggplot objects driven
# entirely by the variable specifications above (see 00_functions.R for full
# details). Panels are named "pca_<label>" for each entry in color_vars, plus
# $scree, $pearson_heatmap, and $kruskal_heatmap.
# ntop controls how many most-variable genes are used; adjust per matrix.

vst_panels <- make_pca_panels(
  mat              = vst,
  metadata         = metadata,
  ntop             = 0.1 * nrow(vst),
  color_vars       = color_vars,
  continuous_vars  = continuous_vars,
  categorical_vars = categorical_vars
)

sva_panels <- make_pca_panels(
  mat              = sva_adjusted,
  metadata         = metadata,
  ntop             = 0.9 * nrow(sva_adjusted),
  color_vars       = color_vars,
  continuous_vars  = continuous_vars,
  categorical_vars = categorical_vars
)

study_panels <- make_pca_panels(
  mat              = study_adjusted,
  metadata         = metadata,
  ntop             = 0.1 * nrow(study_adjusted),
  color_vars       = color_vars,
  continuous_vars  = continuous_vars,
  categorical_vars = categorical_vars
)

# ==============================================================================
# Save figures
# ==============================================================================
# Pass any combination of vst_panels, sva_panels, study_panels to the assembly
# functions. Omit panels_b for a single-matrix figure. Both functions are
# defined in 00_functions.R.
#
#   VST vs SVA-corrected (default):
#     assemble_pca_overview(vst_panels, sva_panels)
#
#   Study-corrected vs SVA-corrected:
#     assemble_pca_overview(study_panels, sva_panels)
#
#   Single matrix (VST only):
#     assemble_pca_overview(vst_panels)
# ==============================================================================

fig_pca <- assemble_pca_overview(
  panels_a = vst_panels,
  panels_b = sva_panels
)

svg("figures/chapter_01/fig_exvivo_normalisation_pca.svg", width = 8.27, height = 11.69)
print(fig_pca)
dev.off()

fig_meta <- assemble_pca_metafeatures(
  panels_a = vst_panels,
  panels_b = sva_panels
)

svg("figures/chapter_01/fig_exvivo_normalisation_pca_metafeatures.svg", width = 11.69, height = 7)
print(fig_meta)
dev.off()